
   
on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: local 
      AWS_SECRET_ACCESS_KEY: local
      DYNAMO_VERBOSE: 1
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run local dynamodb
      run: docker-compose up -d
    - name: Set up local dynamo tables
      run: aws dynamodb create-table --cli-input-json file://invitations-table.json --endpoint-url http://localhost:8000
    - name: Test
      run: go test ./...